# Generated by Django 5.2.3 on 2025-07-04 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical_data", "0001_initial"),
        ("patients", "0005_remove_patient_edad_patient_fecha_nacimiento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicaldata",
            name="age",
            field=models.IntegerField(verbose_name="Edad"),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="alcohol_consumption",
            field=models.BooleanField(default=False, verbose_name="Consumo de alcohol"),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="cholesterol",
            field=models.FloatField(verbose_name="Colesterol"),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="date_recorded",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de registro"
            ),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="diastolic_pressure",
            field=models.FloatField(verbose_name="Presión diastólica"),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="family_history",
            field=models.BooleanField(
                default=False, verbose_name="Antecedentes familiares"
            ),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="gender",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                max_length=10,
                verbose_name="Género",
            ),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="glucose",
            field=models.FloatField(verbose_name="Glucosa"),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="heart_rate",
            field=models.IntegerField(verbose_name="Frecuencia cardíaca"),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_data_records",
                to="patients.patient",
                verbose_name="Paciente",
            ),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="physical_activity",
            field=models.BooleanField(default=False, verbose_name="Actividad física"),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="prediction_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de predicción"
            ),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="previous_conditions",
            field=models.TextField(blank=True, verbose_name="Condiciones previas"),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="risk_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Puntuación de riesgo"
            ),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="smoking",
            field=models.BooleanField(default=False, verbose_name="Fumador"),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="systolic_pressure",
            field=models.FloatField(verbose_name="Presión sistólica"),
        ),
    ]
