# Generated by Django 5.2.2 on 2025-06-06 18:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("apellidos", models.CharField(max_length=200)),
                ("edad", models.IntegerField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")], max_length=1
                    ),
                ),
                ("peso", models.FloatField(help_text="Peso en kilogramos")),
                ("altura", models.FloatField(help_text="Altura en centímetros")),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.TextField(blank=True)),
                ("numero_historia", models.CharField(max_length=50, unique=True)),
                (
                    "hospital",
                    models.CharField(
                        default="Policlínico Laura Caller", max_length=200
                    ),
                ),
                (
                    "external_patient_id",
                    models.CharField(
                        blank=True,
                        help_text="ID del paciente en sistema externo",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "external_system_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos adicionales del sistema externo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["numero_historia"],
                        name="patients_pa_numero__903211_idx",
                    ),
                    models.Index(
                        fields=["external_patient_id"],
                        name="patients_pa_externa_1aba75_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="patients_pa_created_542792_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("presion_sistolica", models.IntegerField(help_text="mmHg")),
                ("presion_diastolica", models.IntegerField(help_text="mmHg")),
                (
                    "frecuencia_cardiaca",
                    models.IntegerField(
                        blank=True, help_text="latidos por minuto", null=True
                    ),
                ),
                (
                    "colesterol",
                    models.FloatField(blank=True, help_text="mg/dL", null=True),
                ),
                (
                    "colesterol_hdl",
                    models.FloatField(blank=True, help_text="mg/dL", null=True),
                ),
                (
                    "colesterol_ldl",
                    models.FloatField(blank=True, help_text="mg/dL", null=True),
                ),
                (
                    "trigliceridos",
                    models.FloatField(blank=True, help_text="mg/dL", null=True),
                ),
                (
                    "glucosa",
                    models.FloatField(blank=True, help_text="mg/dL", null=True),
                ),
                (
                    "hemoglobina_glicosilada",
                    models.FloatField(blank=True, help_text="HbA1c %", null=True),
                ),
                ("cigarrillos_dia", models.IntegerField(default=0)),
                ("anos_tabaquismo", models.IntegerField(default=0)),
                (
                    "actividad_fisica",
                    models.CharField(
                        choices=[
                            ("sedentario", "Sedentario"),
                            ("ligero", "Actividad Ligera"),
                            ("moderado", "Actividad Moderada"),
                            ("intenso", "Actividad Intensa"),
                        ],
                        default="sedentario",
                        max_length=20,
                    ),
                ),
                (
                    "antecedentes_cardiacos",
                    models.CharField(
                        choices=[("si", "Sí"), ("no", "No"), ("desconoce", "No sabe")],
                        default="no",
                        max_length=20,
                    ),
                ),
                ("diabetes", models.BooleanField(default=False)),
                ("hipertension", models.BooleanField(default=False)),
                ("medicamentos_actuales", models.JSONField(blank=True, default=list)),
                ("alergias", models.JSONField(blank=True, default=list)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "external_record_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("external_data", models.JSONField(blank=True, default=dict)),
                (
                    "fecha_registro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
