# Generated by Django 5.2.3 on 2025-06-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_patient_medico_tratante"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="dni",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
