# Generated by Django 5.2.3 on 2025-06-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_patient_dni"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="dni",
            field=models.CharField(
                help_text="DNI del paciente", max_length=20, unique=True
            ),
        ),
    ]
