# Generated by Django 5.2.3 on 2025-07-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_patient_dni"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="edad",
        ),
        migrations.AddField(
            model_name="patient",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="sexo",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                max_length=1,
            ),
        ),
    ]
