# Generated by Django 3.2.24 on 2025-07-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_patient_edad_patient_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='edad',
            field=models.IntegerField(blank=True, help_text='Edad del paciente en años', null=True),
        ),
    ]
