# Generated by Django 5.2.5 on 2025-08-24 15:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0006_medicalrecord_edad"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="colesterol",
            field=models.FloatField(
                default=200.0,
                help_text="mg/dL - OBLIGATORIO para predicción cardiovascular",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="colesterol_hdl",
            field=models.FloatField(
                blank=True, help_text="mg/dL - Opcional", null=True
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="colesterol_ldl",
            field=models.FloatField(
                blank=True, help_text="mg/dL - Opcional", null=True
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="edad",
            field=models.IntegerField(
                default=40,
                help_text="Edad del paciente en años - OBLIGATORIO para predicciones",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="frecuencia_cardiaca",
            field=models.IntegerField(
                default=70, help_text="latidos por minuto - OBLIGATORIO para predicción"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="glucosa",
            field=models.FloatField(
                default=100.0, help_text="mg/dL - OBLIGATORIO para predicción"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="hemoglobina_glicosilada",
            field=models.FloatField(
                blank=True, help_text="HbA1c % - Opcional", null=True
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="presion_diastolica",
            field=models.IntegerField(help_text="mmHg - OBLIGATORIO para predicción"),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="presion_sistolica",
            field=models.IntegerField(help_text="mmHg - OBLIGATORIO para predicción"),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="trigliceridos",
            field=models.FloatField(
                blank=True, help_text="mg/dL - Opcional", null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="fecha_nacimiento",
            field=models.DateField(
                default=datetime.date(1985, 9, 3),
                help_text="Fecha de nacimiento del paciente - OBLIGATORIO para predicciones",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="medico_tratante",
            field=models.ForeignKey(
                help_text="Médico tratante - OBLIGATORIO para seguimiento",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patients_treated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="sexo",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                help_text="Sexo del paciente - OBLIGATORIO para predicciones",
                max_length=1,
            ),
        ),
    ]
