# Generated by Django 3.2.24 on 2025-09-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_medicalrecord_colesterol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, help_text='latidos por minuto - Opcional', null=True),
        ),
    ]
