# Generated by Django 5.2.2 on 2025-06-06 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_recorded", models.DateTimeField(auto_now_add=True)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=10,
                    ),
                ),
                ("smoking", models.BooleanField(default=False)),
                ("alcohol_consumption", models.BooleanField(default=False)),
                ("physical_activity", models.BooleanField(default=False)),
                ("systolic_pressure", models.FloatField()),
                ("diastolic_pressure", models.FloatField()),
                ("heart_rate", models.IntegerField()),
                ("cholesterol", models.FloatField()),
                ("glucose", models.FloatField()),
                ("family_history", models.BooleanField(default=False)),
                ("previous_conditions", models.TextField(blank=True)),
                ("risk_score", models.FloatField(blank=True, null=True)),
                ("prediction_date", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_data_records",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dato Médico",
                "verbose_name_plural": "Datos Médicos",
                "ordering": ["-date_recorded"],
            },
        ),
    ]
